# Generated by Django 5.1.1 on 2024-09-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('criador', 'criador'), ('visitante', 'visitante')], max_length=10, verbose_name='tipo do usuario')),
                ('name', models.CharField(max_length=100, verbose_name='nome do evento')),
                ('description', models.CharField(max_length=200, verbose_name='descrição do evento')),
                ('date', models.DateTimeField(verbose_name='data do evento')),
                ('local', models.CharField(max_length=100, verbose_name='local do evento')),
                ('max_capacity', models.IntegerField(verbose_name='capacidade maxima')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.events', verbose_name='evento')),
            ],
        ),
    ]
