# Generated by Django 5.1.1 on 2024-09-06 21:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_creator', models.BooleanField(default=False, verbose_name='criador')),
                ('is_visitor', models.BooleanField(default=False, verbose_name='visitante')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo do cancelamento')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.events', verbose_name='evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users', verbose_name='usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Cancellation',
        ),
    ]
