# Generated by Django 5.1.1 on 2024-09-09 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_remove_events_user_remove_events_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data final do evento'),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do inicio do evento'),
        ),
    ]
